### ISSUE TITLE
Feature Request: Remove "Bastards" who are not following you back

### ISSUE THREAD

**Issue by WardenCommander** [goodwin64/instagram-not-mutual-followers#1]
could you add feature to Remove "Bastards" who are not following you back

**Comment by goodwin64** [comment]
Hi,

do you mean the feature to automatically unsubscribe from these users?

**Comment by WardenCommander** [comment]
Yes.
Right now Im using your original code. as one that you put on greasyfork is not working for me.

https://greasyfork.org/en/scripts/399405-instagram-not-mutual-followers

**Comment by WardenCommander** [comment]
This is Error/warning I get when i run your script on Chrome/tampermonkey

DevTools failed to parse SourceMap: webpack:///node_modules/@typed/compose/lib.es2015/index.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/@typed/compose/lib.es2015/compose.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/lines-unlines/dist/index.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/ts-type-guards/dist/index.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/ts-type-guards/dist/is.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/ts-type-guards/dist/array.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/ts-type-guards/dist/only.js.map

**Comment by WardenCommander** [comment]
Ok, figure it out, now its working message is still showing but button is here.

**Comment by goodwin64** [comment]
I'll double-check it on my laptop, seems like source maps issue. 

Yeah, I can add this feature. Roughly in 2 days (will be available on Apr 10-11).

**Comment by goodwin64** [comment]
Dug into this a little. I think it will be delayed for the next weekends (Apr 18-19 or 25-26).

**Comment by WardenCommander** [comment]
Hey @goodwin64 

I used your original code and, expand it with 2 new buttons
one for removing people. and one for extracting images
where Im tagged and pictures that I published.
I have a problem that function doesnt "wait" for GetAllPictures() to finish
but it executes commands.
console.log(UserPicture),
console.log(UserTaggedPicture),

What im trying to do is extract images, and from them who liked, and who comment on them.
to use that leads for future follow and unfollow option. Im sending you your modified script. If you
want to take a look.
[Script.txt](https://github.com/goodwin64/instagram-not-mutual-followers/files/4491469/Script.txt)


function createBotPictureTag() {
  let isEnabled = false;

  const api = {
    startBot: () => {
      if (isEnabled) {
        return;
      }
      GetAllPictures()
        .then(([UserPicture, UserTaggedPicture]) => [
          console.log(UserPicture),
          console.log(UserTaggedPicture),
        ])
        .then(([UserPicture, UserTaggedPicture]) => {
          api.stopBot();
          console.log(UserPicture);
          console.log(UserTaggedPicture);
          localStorage.setItem("MyPictures",JSON.stringify(UserPicture));
          localStorage.setItem("MyTaggedPictures",JSON.stringify(UserTaggedPicture));
          //TEST("MyPictures","MyTaggedPictures");
        });
    },
    stopBot: () => {
      clearInterval(isEnabled);
      isEnabled = null;
    },
    isEnabled: () => Boolean(isEnabled),
  };

  return api;
}

**Comment by goodwin64** [comment]
@WardenCommander issue is solved, please check it out.
