### ISSUE TITLE
Troubles understanding extension usage

### ISSUE THREAD

**Issue by pidgeon777** [goodwin64/instagram-not-mutual-followers#2]
Hello, I would like to ask how this extension is supposed to work. When I enable it, the only thing added I can notice is the leftmost icon here:

![image](https://user-images.githubusercontent.com/13739892/79008449-b958c900-7b5d-11ea-943e-bdc5a0b7d224.png)

But when I click on it, nothing happens.

**Comment by goodwin64** [comment]
Hi @pidgeon777! Glad to know someone is using this script.

It worth adding some user manuals to save time and make usage more convenient, so I'll do it soon anyway.

Some screenshots will answer your questions easily:
## navigate to user profile, click helper button
![image](https://user-images.githubusercontent.com/10671879/79011446-b5807300-7b6c-11ea-8dd7-7c5cf641ff80.png)

## wait for a notification
![image](https://user-images.githubusercontent.com/10671879/79011505-dfd23080-7b6c-11ea-9c96-3203cb38d73d.png)

## open dev tools
![image](https://user-images.githubusercontent.com/10671879/79011746-58d18800-7b6d-11ea-97e7-72d4c8fc2de7.png)

## see the lists of users
![image](https://user-images.githubusercontent.com/10671879/79011546-f6788780-7b6c-11ea-8840-ece752f4e5dc.png)

## for instance, these users do not follow me, while I follow them (usually celebrities or people that use Instagram rarely or haven't noticed my following request)
![image](https://user-images.githubusercontent.com/10671879/79011608-0abc8480-7b6d-11ea-91cf-dd0ab1eee477.png)
![image](https://user-images.githubusercontent.com/10671879/79011807-874f6300-7b6d-11ea-8c83-25b6865ca9f0.png)

**Beware** that this script works only in a web view, NOT within Android/iOS app.

**Comment by pidgeon777** [comment]
First of all, thanks for the nice guide. Regarding your script popularity, for sure it deserves more visibility. I'm confident it will improve in the upcoming weeks.

I tried as you suggested, but as soon as I click on the "Start analyzing" button, the following error message appears in the console:

![image](https://user-images.githubusercontent.com/13739892/79043597-62f09680-7c00-11ea-847a-efecaafff2df.png)

I tried this when loading these pages:

- https://www.instagram.com/
- https://www.instagram.com/my_username

But the outcome is the same.

I installed your script from here:

https://greasyfork.org/en/scripts/399405-instagram-not-mutual-followers

**Comment by goodwin64** [comment]
Oh, I checked it right now and this but is reproduced on my computer as well. Thanks for reporting!

It looks like I haven't took into account usernames with numbers and this analyzer couldn't parse the username from the URL. Fix will be available soon, I'll notify you in this thread.

**Comment by pidgeon777** [comment]
Thank you. I'll ask another question, about updating the script.

As I stated before, I downloaded and installed it starting from the greasyfork.org website.

My question is, does it supports auto-updating? I mean, when you update your GitHub repository, will my installed script also receive the update? (I use Tampermonkey).

**Comment by goodwin64** [comment]
I'm also interested in auto updates, currently I don't yet know whether it's possible. Before I've updated it manually from the GreasyFork each time I publish a new version. I'll also notify you if I find something.

**Comment by goodwin64** [comment]
@pidgeon777 the answer on your last question:
there is no such a possibility for auto-updates. It's tenable, otherwise, developers will hack user accounts without letting them know.

But users can update scripts from Tampermonkey dashboard, like so:
![image](https://user-images.githubusercontent.com/10671879/79682880-9fd71180-822e-11ea-8e7a-27c5d658daa7.png)

![ezgif-5-6d829069bdd4](https://user-images.githubusercontent.com/10671879/79682890-ad8c9700-822e-11ea-8b45-fa4cfd4ba5bd.gif)

**Comment by goodwin64** [comment]
@pidgeon777 docs are now more clear, I think. Please ping me if something has to be clarified.

**Comment by pidgeon777** [comment]
First of all, absolutely great work. Many improvements have been made and now the script is even useful than before.

I've just a question: does the "Only if they follow me" column report the users who follow me but that I do not follow back?

**Comment by goodwin64** [comment]
Yes, exactly, users from this column follow you, but you're not follow them.
