### ISSUE TITLE
Build is too large, tree shaking isn't applied

### ISSUE THREAD

**Issue by goodwin64** [goodwin64/instagram-not-mutual-followers#5]
Investigate how to apply tree shaking so Material UI and other dependencies won't be included entirely, but only required sub-packages.

2 obvious benefits:
1. The build size will be smaller 
2. Easier to deliver and test

**Comment by AGenchev** [comment]
Yes this is the first *monkey extension I saw whose code is scattered over so many small files. I gave up on trying to understand what happens...
maybe I'm too old and this is the new fashion in programming.

**Comment by goodwin64** [comment]
:)

Just for the purpose of quick scaffolding I used giant Material UI library with React+Preact (and preact-compat) for UI layer. Theoretically, they can bad omitted and code bundle will be lightweight but I'm sure development will be slower as well.

**Comment by goodwin64** [comment]
One more reason to solve this issue:

![image](https://user-images.githubusercontent.com/10671879/79681099-bb86eb80-821f-11ea-9ec8-e5e6c1b1e193.png)
